config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id, message: "is already in the list"

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  # should destroy child saved movies when destroying self
  # When you delete a list, you should delete all associated bookmarks
  # (but not the movies as they can be referenced in other lists).
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
  # validates :name, uniqueness: { case_sensitive: false }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]

  # GET "lists/:id/bookmarks/new"
  def new
    @bookmark = Bookmark.new
  end

  # POST "lists/:id/bookmarks"
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  # DELETE "bookmarks/:id"
  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/:id
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # POST "lists"
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE "lists/:id"
  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('cover.jpg') %>)">
  <div class="container">
    <h1 class="p-500">Your Favourite WatchList</h1>
  </div>
</div>
<div class="container">
  <h1>My lists</h1>
  <div class="cards">
    <% @lists.each do |list|%>
    <div class="card-category h-120" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('list_background.jpg') %>)">
      <div class="button"><%= link_to list.name, list_path(list), class: "nav-link" %></div>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Create new list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h2>LIST:<%= @list.name %></h2>
<br>
<h3>Bookmark</h3>
<p><%= link_to "Add a bookmark", new_list_bookmark_path(@list) %></p>
<div class="container">
 <% @list.bookmarks.each do |bookmark|%>
  <label class="form-control">
    <p>COMMENT:<%= bookmark.comment %></p>
    <p>MOVIE:<%= bookmark.movie.title %></p>
<div class="red-text"><%= link_to "Remove",bookmark_path(bookmark),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></div>
  </label>
<% end %>
</div>
<%= link_to "Back Home", lists_path %>